name: in_app_purchase_platform_interface
description: A common platform interface for the in_app_purchase plugin.
repository: https://github.com/isaacy13/packages-themedeck/tree/remote-hotfix/packages/in_app_purchase/in_app_purchase_platform_interface
issue_tracker: https://github.com/isaacy13/packages-themedeck/issues
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 1.4.0

environment:
  sdk: ^3.2.5
  flutter: ">=3.16.8"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

topics:
  - in-app-purchase
  - payment
